name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish workshop2_vs.sln
      
#    - name: Easy Zip Files
#      uses: vimtor/action-zip@v1 

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: workshop2_vs.sln
        
    - uses: actions/checkout@v2

    - name: Upload a file to Google Drive
      uses: willo32/google-drive-upload-action@v1
      with:
        target: my-artifact.zip
        credentials: ${{ secrets.luongphuckhang200300hiie@gmail.com }}
        parent_folder_id: 1X7Wc9EU3vLPA5uh1YWSsyWuWTqXTVgXx
